project_id = "zvjasfcntrkfrwvwzlpk"

[functions.ai-diagnosis]
verify_jwt = true

[functions.diagnose]
verify_jwt = true

[functions.diagnose-symptoms]
verify_jwt = false

[functions.diagnose-symptoms-secure]
verify_jwt = true

[functions.diagnose-with-validation]
verify_jwt = true

[functions.drug-recommendations]
verify_jwt = false

[functions.get_medications_with_condition]
verify_jwt = true

[functions.save-diagnosis]
verify_jwt = true

[functions.recommend-drug]
verify_jwt = true

[functions.doctor-actions]
verify_jwt = true

[functions.doctor-diagnosis-actions]
verify_jwt = true

[functions.secure-doctor-actions]
verify_jwt = true

[functions.create-notification]
verify_jwt = false

[functions.create-audit-log]
verify_jwt = false

[functions.system-health-check]
verify_jwt = false

[functions.qa-testing-runner]
verify_jwt = true

[functions.generate-questions]
verify_jwt = true

[functions.get-results]
verify_jwt = true

[functions.daily-health-tip]
verify_jwt = false