project_id = "zvjasfcntrkfrwvwzlpk"

[functions.ai-diagnosis]
verify_jwt = true

[functions.diagnose]
verify_jwt = true

[functions.diagnose-symptoms]
verify_jwt = false

[functions.drug-recommendations]
verify_jwt = false

[functions.save-diagnosis]
verify_jwt = true

[functions.doctor-actions]
verify_jwt = true

[functions.create-notification]
verify_jwt = false

[functions.create-audit-log]
verify_jwt = false
