INSERT INTO public.facilities (name, type, address, city, state, country, phone, email, description, latitude, longitude, is_active) VALUES
('Lagos University Teaching Hospital', 'hospital', '1 Idi Araba Rd, Surulere', 'Lagos', 'Lagos', 'Nigeria', '+234-1-480-0100', 'info@luth.gov.ng', 'Premier teaching hospital offering comprehensive medical services.', 6.5095, 3.3711, true),
('National Hospital Abuja', 'hospital', 'Plot 132, Central District', 'Abuja', 'FCT', 'Nigeria', '+234-9-523-4501', 'info@nationalhospital.gov.ng', 'Federal government hospital providing specialized healthcare.', 9.0579, 7.4951, true),
('St. Nicholas Hospital', 'hospital', '57 Campbell St, Lagos Island', 'Lagos', 'Lagos', 'Nigeria', '+234-1-263-0070', 'contact@stnicholas.com.ng', 'Private hospital with modern facilities and expert care.', 6.4541, 3.3947, true),
('MedPlus Pharmacy', 'pharmacy', '12 Admiralty Way, Lekki', 'Lagos', 'Lagos', 'Nigeria', '+234-1-295-0001', 'info@medplusng.com', 'Chain pharmacy with wide range of medications and health products.', 6.4315, 3.4714, true),
('HealthPlus Pharmacy', 'pharmacy', '25 Isaac John St, GRA Ikeja', 'Lagos', 'Lagos', 'Nigeria', '+234-1-271-2222', 'hello@healthplus.com.ng', 'Nigeria''s leading retail pharmacy chain.', 6.5728, 3.3515, true),
('Reddington Hospital', 'hospital', '12 Idowu Martins St, Victoria Island', 'Lagos', 'Lagos', 'Nigeria', '+234-1-271-5555', 'info@reddingtonhospital.com', 'Multi-specialty hospital with world-class healthcare.', 6.4281, 3.4219, true),
('Cedarcrest Hospital', 'hospital', '1 Cedarcrest Close, Gudu', 'Abuja', 'FCT', 'Nigeria', '+234-9-290-0900', 'info@cedarcresthospitals.com', 'Private multi-specialty hospital in Abuja.', 9.0105, 7.4585, true),
('Alpha Pharmacy', 'pharmacy', '45 Allen Ave, Ikeja', 'Lagos', 'Lagos', 'Nigeria', '+234-1-497-0001', 'contact@alphapharmacy.ng', 'Trusted community pharmacy with professional pharmaceutical care.', 6.5963, 3.3462, true),
('Evercare Hospital', 'hospital', '1 Admiralty Rd, Lekki Phase 1', 'Lagos', 'Lagos', 'Nigeria', '+234-1-291-6100', 'info@evercare.ng', 'International standard hospital with cutting-edge technology.', 6.4440, 3.4735, true),
('Total Health Clinic', 'clinic', '8 Opebi Road, Ikeja', 'Lagos', 'Lagos', 'Nigeria', '+234-1-342-1100', 'hello@totalhealthclinic.ng', 'Modern outpatient clinic offering primary and specialist care.', 6.5832, 3.3521, true);
