// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvjasfcntrkfrwvwzlpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2amFzZmNudHJrZnJ3dnd6bHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzQzMjAsImV4cCI6MjA2NzIxMDMyMH0.8h9rzV0-3B71alwJAjQ7QdFfDC0WiHRQdOP30GHhVlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});